language: python
python:
  - "2.7"
  #- "2.6"
  #
virtualenv:
  system_site_packages: true

install:
  - "sudo apt-get install -qq python-numpy python-scipy"
  #- "pip install -r requirements.txt --use-mirrors"
  - "pip install nose-exclude sphinx --use-mirrors"

script: 
  - python -c 'import numpy; print numpy.version.version'
  - python -c 'import scipy; print scipy.version.version'
  - nosetests
  - cd doc; make doctest
